---

- name: create working directory
  file: path={{ working_dir }} owner={{ user }} state=directory mode=0775

- name: create install directory
  file: path={{ install_dir }} owner={{ user }} state=directory mode=0775

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - mysql-server
    - python-mysqldb
    - php5-mysql
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags: mysql-server



#- name: download mysql
#  get_url: url={{ mysql_url }} dest={{ working_dir }} owner={{ user }} mode=0775

#- name: extract mysql
#  unarchive: src={{ working_dir }}/{{ mysql_zip_name }} dest={{ install_dir }} copy=no



