---

- name: update apt
  apt: update_cache=yes cache_valid_time=3600

- name: install dependencies
  action: apt pkg={{ item }} state=present
  with_items: "{{ packages }}"

- name: test zookeeper
  shell: nc -zv {{ inventory_hostname }} 2181
